title: ielab
description: Information Engineering Lab.
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  - jekyll-scholar

scholar:
  style: assets/bibliography/acm-sig-proceedings.csl
  locale: en

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  source: _bibliography
  repository: pdf
  bibliography: references
  bibliography_template: bibliography

  replace_strings: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"